### ISSUE TITLE
Any way to know the final number of SCGs used in the concatenated alignment

### ISSUE THREAD

**Issue by Anto007** [AstrobioMike/GToTree#1]
GToTree is a fantastic tool- I just happened to test it out! I was wondering if there's any way to know the final number of SCGs used in the concatenated alignment? For example, I used for my analysis the Bacteria.hmm with 74 targets but I'm not sure how many out of the 74 SCGs were used in the final concatenated alignment since the console output reported that not all 74 SCGs were detected for all of my 150 input genomes. It will definitely be useful to know how many SCGs were taken into account for the final alignment. Many thanks.

**Comment by AstrobioMike** [comment]
Thanks for the kind words! If you're talking about SCGs not found in _any_ of the input genomes, I don't know why I didn't put that info into an output file rather than just printing it to the console, ha, so thanks for the suggestion :) There's now an output file containing a list of those not found in any genome (if there were any). If you do a fresh [install](https://github.com/AstrobioMike/GToTree/wiki/Installation) of version 1.0.6, it will be reported. (If you don't want to do a fresh install and re-run, the output table "All_genomes_SCG_hit_counts.tsv" can tell you which weren't found in any genomes - those with 0 for all genomes).

If you're talking about SCGs not being found in _some_ genomes, those are still used in the final alignment, just with gap-sequences for the genomes that don't have them. And which genomes are missing which genes can be found in the "All_genomes_SCG_hit_counts.tsv" output file. 

If you're talking about something else and I'm misunderstanding, please do let me know :)

**Comment by Anto007** [comment]
Many thanks for your prompt clarification! Just one last question: What happens to the SCGs detected on my input genomes in >1 copy, for e.g., 2 or 3 copies? I hope GToTree treats them just as it is with zero counts i.e., inserting gaps for the genomes that have these SCGs in multiple copies?

**Comment by AstrobioMike** [comment]
You know it doesn’t do that right now, it just takes the best hit. I made that choice because the way the single-copy gene-sets were made is by taking those that have exactly 1 hit to a pfam-HMM in greater than 90% of the ~12,000 searched genomes – some legit have more than one hit and filtering that way can end up removing a lot in some genomes. So my thinking is the best hit should be from the protein that is under similar evolutionary pressures to those that built the HMM model.

But thanks for asking about this. I’m gonna add in an option to only keep those that have single hits so people can make the call themselves. I’ll let you know when it’s in there :)

Thanks!

**Comment by AstrobioMike** [comment]
Added in as the **`-C`** flag for "conservative mode" in versions 1.0.8+ :)
https://github.com/AstrobioMike/GToTree/commit/a1c32a92e5d0e652c972640b82514f22f7706459

And explained here:
https://github.com/AstrobioMike/GToTree/wiki/Things-to-consider#conservative-mode

Putting an option in for this has crossed my mind a few times, but it was easier to be lazy about it when it was just a passing thought by me, ha. Thanks for bringing it up!

**Comment by Anto007** [comment]
This is awesome. Thank you very much! Keep up the great work

**Comment by AstrobioMike** [comment]
UPDATE: 
From v1.1.1 on, the **default** behavior is GToTree will **not** use a gene from a given genome if there was more than one hit to the target HMM profile, and rather insert a gap-sequence and treat it as though no hits were found. After some more thought it seems to be better to be conservative when talking about default settings rather than not, which I gather was kind of your point from the start :) 

Now specifying the "-B" flag will let it run in "best-hit mode" and use the best hit of multiple targets if desired ([https://github.com/AstrobioMike/GToTree/wiki/things-to-consider#best-hit-mode](https://github.com/AstrobioMike/GToTree/wiki/things-to-consider#best-hit-mode))

The final output genome summary table also now lists how many of the target genes each input genome actually contributed to the final alignment. 

Thanks again, @Anto007!

**Comment by Anto007** [comment]
I really liked your decision to go with being conservative for the default behavior-Fantastic! I had exactly this in mind when I started this thread but I didn't wanna push you on the same ;-)
