### ISSUE TITLE
Any ideas for automated generation of a taxon name mapping file?

### ISSUE THREAD

**Issue by Anto007** [AstrobioMike/GToTree#12]
Hi Mike,

I was wondering if you would have any ideas on how to conveniently mass-generate a mapping file (genome_to_id_map.tsv) for using the -m  flag on GToTree (as I don't want to sit and manually edit the tree taxa names)? For example, I'm making a tree which has got several hundred genomes on it and all that I have got are genome files with their accession numbers appearing as part of their file names (say for example, 'GCF_000379705.1_ASM37970v1_genomic.fasta'). My genome_to_id_map.tsv should like below:

GCF_000379705.1_ASM37970v1_genomic.fasta                Corynebacterium caspium DSM 44850

I guess efetch would be an approach to go about this but I would appreciate it very much if you have any (straightforward) pointers here? (feeling a bit lazy this afternoon ;-) and I reckoned that you might have an easy/convenient solution for this!). Thanks in advance for your kind response.

**Comment by AstrobioMike** [comment]
Hi there!

Does adding lineage info specifying Species and Strain get what you want? 

E.g. providing these arguments to the GToTree call: `-t -L Species,Strain`

**Comment by AstrobioMike** [comment]
Oh, and if you don't want the assembly accession number there up front (though without it there may be some duplicates, i don't know off the top of my head if that might cause problems somewhere in GToTree or elsewhere), i would run it once that way (no mapping file), and then parse the main genome summary output file after the first run to make the mapping file. In the "Genomes_summary_info.tsv" file, the first two columns are the assembly ID (accession or file name) and then the label that was put on the tree. So you could chop that up with some bash to get rid of the leading accessions in the second column there and that'd be your mapping file for a new run (let me know if you'd like some help with that!)

This would take running things twice, but takes advantage of getting the strain info already being coded within GToTree, which can kind of be a pain. You can probably do it with `efetch` like you mentioned, i think we can do everything with edirect, if we spend enough time banging our head against the keyboard, haha. I'd have to mess with it too to figure out if we can and how that way

**Comment by Anto007** [comment]
As always, thank you so much for your super-quick response Mike. I'm sorry I missed to mention in my earlier post that the only reason I was taking the -m route is cos when I do  the "-t -L Species,Strain" option, I get the below error at the second-last last step of the run:
####                   Adding more informative headers                    ####
cat: 1574316930.gtotree.tmpdir/final_taxonkit_id_swap_map.tmp: No such file or directory

For example, when I do "GToTree -f fasta_list.txt -H /home/antonycp/tools/GToTree-1.1.1/hmm_sets/Bacteria.hmm -j 8 -t -L Species,Strain -m genome_to_id_map.tsv -o tree_output", I get only that which is mentioned on the tsv file actually renamed on the final tree. Thanks again for helping me out here- much appreciated!

**Comment by AstrobioMike** [comment]
Oh no! There’s a bug I need to track down I think, thanks for letting me know!

So the taxonomy swap won’t work for input genomes provided as fasta files, it only works for those provided as NCBI accessions. I wasn’t being observant enough at first that you were providing a genome with an NCBI accession as a flat fasta file, sorry!

I realize you may have these downloaded already, but if they are just the fasta files from ncbi assemblies, the lineage info should get added properly if you just provide the accessions as input to GToTree rather than fasta files. So a single column file with them in each row, e.g.:

GCF_000379705.1
GCF_000379BLA.1
etc. 

GToTree doesn’t try to parse fasta file inputs to see if they have taxonomy associated with them


All that aside there is still a problem/bug in there that shouldn’t be trying to run that `cat` command if there aren’t any to be swapped. I’m gonna look into that ASAP!

Is there some reason you’re providing ncbi genomes in fasta form rather than a list of accessions to the `-a` argument?

**Comment by AstrobioMike** [comment]
Oh and definitely reinstall the latest GToTree if possible (conda is the best way) :)

**Comment by Anto007** [comment]
Thanks Mike. I'll now try with the -a flag instead of using the -f flag. I had used ncbi-genome-download to bulk download all the genomes of interest and once I had the fasta files, I just decided to use the -f flag since the files were already available. Didn't realize that -a flag would work best here. I would like to take this opportunity to suggest an enhancement for your cool tool (of course you're free to reject this idea!): What about having an additional module for making a 16S rRNA-gene-based tree from all the input genomes? I don't think there's a tool out there now that can do this in a straightforward manner? If this is also made available under GToTree, I would expect GToTree to become doubly useful for users to construct trees at the level of 16S rRNA gene as well as SCGs. A 16S rRNA-based tree is relevant since many microbes are still represented by only this gene sequence (and not the genome sequence) and microbiology scientists often demand to see 16S trees when some or several relevant members of the microbial group members under study haven't got their genomes sequenced. I think one way you could incorporate this into GToTree would be by using barrnap and bedtools to parse out the 16S rRNA gene sequences; assigning taxonomic labels to the sequences and then also providing the option for users to supply an additional 16S multi-fasta file (which have all 16S sequences of taxa that do have not their genomes sequenced) and then constructing a final tree from all these inputs

**Comment by Anto007** [comment]
Tried the -a flag and taxon names appear correctly on the final tree now. Thanks a ton!

**Comment by AstrobioMike** [comment]
Sweet!

Regarding the initial bug you hit:

>Adding more informative headers
>cat: 1574316930.gtotree.tmpdir/final_taxonkit_id_swap_map.tmp: No such file or directory

I'm happy to say that was fixed sometime between v1.1.1 and current (v1.4.7), as i get the same error when running v1.1.1, but now see this instead when running the current version:

![image](https://user-images.githubusercontent.com/13923308/69367085-70ef4c00-0c4c-11ea-97e9-05dac2bde69c.png)

So good job, past-Mike, haha

I appreciate and like your suggestion about outputting 16S trees too, and agree it's often a request by reviewers and others, and can be of some interest in comparing to phylogenomic trees, but i had very mixed feelings about actually implementing it when I first read it. So i slept on it, and i still have very mixed feelings, haha. It's a lot to convey that i don't have completely sorted out in my head yet either, but it's complicated to me for programmatic reasons and in terms of thinking i have something to contribute by including it. Programmatic-wise, 16S genes are hard to recover from genomes derived from metagenomes (so they may or may not be in many genomes input, and may or may not be accurate), and also in addition to multiple copies, lots of genomes have different copies, so choosing which one to include seems like something i wouldn't want to be involved in, haha. The other side of "in terms of thinking i have something to contribute", for a long time i didn't officially "put together" GToTree because i felt a little like i wasn't doing anything. It's wrapping other tools and doing some basic calculations underneath. I finally got over that and am glad I did as I think it is helpful to lots of people and their science (including myself, ha), but pulling out 16S genes and treeing them seems like a smaller step that maybe I shouldn't just roll into GToTree. 

Those thoughts aren't exhaustive, or fully fleshed out in my own head yet, so i'm sorry if they seem scattered and not very intelligible. But i like the idea and wanted to let you know where i was on it currently. I don't know if i'll feel differently about it tomorrow or next week, but either way i appreciate your voicing it and it will certainly be bouncing around in my head for the foreseeable future :)

**Comment by Anto007** [comment]
Thanks Mike for your kind reception (as always) to my suggestion- You're a good man! I certainly don't intend to push you on this. I will try to update my GToTree version to v1.4.7 right away to get rid off the bug. Thanks again for your 100% sincerity!
