### ISSUE TITLE
Proteins with multiple domains

### ISSUE THREAD

**Issue by adityabandla** [AstrobioMike/GToTree#18]
Hi Mike

I'm trying to understand how GToTree handles the case (especially for completion and redundancy) when there are multiple domains in the same protein. For instance, if you have a look at the domain organisation for ribosomal L6 (PF00347), there are numerous sequences which have >1 domain.

Regards, Adi

**Comment by AstrobioMike** [comment]
Hey there, Adi!

Good observation! In terms of estimates of completion/redundancy, even if a protein has multiple copies of the same domain within it, it counts as only 1 gene-copy in the calculations. 

I noticed this too and thought about it for a little bit while putting together the [single-copy gene sets](https://github.com/AstrobioMike/GToTree/wiki/SCG-sets). You probably saw on that page that i filtered out PFams that didn't cover more than 50% of the underlying protein sequences that go into that HMM, to ensure that no single protein had more than one _different_ PFam domain in it. But as you caught onto here, that doesn't account for those with more than one of the _same_ PFam hit. In the ribosomal L6 example you noted, looking at the [curation & model page](https://pfam.xfam.org/family/PF00347#tabview=tab6), it still notes that the average coverage of the underlying sequences by the domain is 77.53% (currently), despite an individual domain covering less than half in so many of the underlying sequences. I decided to keep these in the end because i think it still makes sense if that's the "norm" for that particular "single-copy gene", and i hope we are still able to filter out any potentially anomalous ones to some extent with the `-c` parameter (which sets the acceptable range about the median length of all identified copies of each target single-copy gene). 

That help? 
-Mike

**Comment by adityabandla** [comment]
Thanks Mike, that explains. 
I also noticed that in the Hug et al universal HMM set, for ribosomal L18, you have PF17135, however, this model encompasses only Eukaryotes and Archaea?

**Comment by AstrobioMike** [comment]
Hey Adi :)

As designing a new universal set the same way [I did the others](https://github.com/AstrobioMike/GToTree/wiki/scg-sets) wasn’t effective due to the divergence across the 3 domains, I did my best to get what was used there in Hug et al. 2016

Looking quickly again now and attempting to retrace how I likely ended on using that specific Pfam, I don’t see any L18 Pfams that are ideal: PF00861 captures mitochondria and chloroplasts; PF14204 also hits L5; and PF01775 is also just arc and some euks it seems. So rather than dumping it altogether, I went with what seemed to me to be the least problematic while maintaining the genes from the paper I was citing. I realize just dropping also wouldn’t have been too big of a deal, I can’t remember if I looked and it was an important one in terms of how many were being found in both archaea and euks ¯\_(ツ)_/¯ 

I’m definitely open to improving the universal set though. You have some thoughts/suggestions on it?

**Comment by adityabandla** [comment]
Thanks, Mike for providing context! I was expecting it to work out of the box, but didn't give too much thought on the mechanics initially. But yes, given the approach that you took, I agree that this is the best possible solution. IMO, if this can be made clear in the documentation, I think it will be very useful for everyone.

The only workaround that I could find is to switch to other marker sets (for example the GTDB ones) which are more accurate as they rely on the domain-specific sets available on TIGRFAM

**Comment by AstrobioMike** [comment]
I somehow missed the end of this before, Adi, when you say for example GTDB, they rely on domain-specific sets when making a domain-specific tree, not when making a universal tree, correct? 

GToTree is primarily about making the tree, not about estimating completeness/redundancy. I don't think we can make a tree spanning all 3 domains with domain-specific markers. But GToTree also has domain and other taxa-level specific gene-sets in it too (again not engineered for estimating completion/redundancy though, engineered for treeing, though my cyanobacterial set would be more useful for estimating completion/redundancy of a cyanobacteria than a domain-specific bacterial gene-set would be).

Does that make sense, or am i confused? :)
