### ISSUE TITLE
GTDB Downloads

### ISSUE THREAD

**Issue by zpimentel** [AstrobioMike/GToTree#25]
Hi @AstrobioMike,

Thanks for all of your work on GToTree, it has been really useful!

I've been using the new GTDB download option which is a really awesome feature. When I have been using it on the Flavobacteriales I run into download issues for 366 of the 1304 genomes. 

The commands that I ran were:
`gtt-get-accessions-from-GTDB -t Flavobacteriales --GTDB-representatives-only`
`GToTree -a GTDB-Flavobacteriales-order-GTDB-rep-accs.txt -H Bacteroidetes`

I updated this morning to v1.5.36.

The error I run into looks like this:
```
   --------------------------------------------------------------------------   
	On assembly GCA_000520955.1; Number 112 of 1304 total.
   --------------------------------------------------------------------------   

gunzip: 1602623976.gtotree.tmpdir/GCA_000520955.1_genes2.tmp.gz: not in gzip format
Traceback (most recent call last):
  File "/anaconda3/envs/gtotree/bin/gtt-rename-fasta-headers", line 21, in <module>
    in_fasta = open(args.input_fasta, "r")
FileNotFoundError: [Errno 2] No such file or directory: '1602623976.gtotree.tmpdir/GCA_000520955.1_genes2.tmp'
     ******************************* NOTICE *******************************  
	  GCA_000520955.1's genes nor genome downloaded properly :(

	    Reported in "gtotree2/run_files/NCBI_accessions_not_downloaded.txt"
     ************************************************************************ 
```
When I look in ./1602623976.gtotree.tmpdir the file is still compressed - "GCA_000520955.1_genes2.tmp.gz" because it is not in gzip format. When I open the gz file it says "The requested URL was not found on this server."

Any assistance would be greatly appreciated! Thanks again for all of your work!

Best,
Zach Pimentel

**Comment by AstrobioMike** [comment]
Thanks so much, Zach! 

This was a slippery little thing to track down! I'm so glad you wrote in about it and gave me all the info you that you did, pointing me as close as possible to tracking down the odd confluence of things that led to this little bugger :) 

It is fixed as of version 1.5.37 which is available on conda as of now 👍 

Here's the gist if curious: 
First thing is a little while back i added an option to download files over http if ftp wasn't available (i've only seen this in a binder, but i figured why not add it since i realized i could). It turns out that when trying to download a file via _http_, if it doesn't exist, it still makes the file on our system like you saw – just saying it wasn't found. But when trying to download a file via _ftp_, it doesn't create the file on our system if there is nothing to download. Since ftp was how i implemented things originally, my only check in place when trying to pull the amino-acid sequences was to see if the file existed locally and had _something_ in it after the download, anything in it. This was a problem for http, but not a problem for ftp. Now we check if it exists _and_ is a gzipped file type, covering either http or ftp download routes. 
Second thing is, of course you weren't using the `-P` flag to specify to download over http anyway, so it shouldn't have been a problem here anyway. But it turns out that with how i had things implemented, the http setting was accidentally being used by default if _not_ running things in parallel – but ftp was being used by default if things were being run in parallel (e.g. adding `-j 4` to the call). That's fixed now too thanks to you :)
So i missed this entirely because when i tested accessions with no amino-acid seqs, i was testing with ftp. And when i tested the http transfer, i wasn't testing accessions with no amino-acid seqs. Amateur hour over here! 

Thanks again!

**Comment by zpimentel** [comment]
Great, just tried it out and and it works now! Thanks!

Running these genomes through prodigal makes sense. Something to maybe consider in the future is that for the example I gave (GCA_000520955.1) there is a corresponding amino acid sequence file in RefSeq but not in GenBank.

Thanks again!

**Comment by AstrobioMike** [comment]
Yeah good catch, I've noticed that before too on some. I decided not to automatically switch what the user provided in case it matters and they really want the genbank version over refseq for some reason. I don't know if that's best, just what i settled on ¯\_(ツ)_/¯
