### ISSUE TITLE
Can't' find unzip_rename_cat_genes.sh mentioned in the SCG set instruction page

### ISSUE THREAD

**Issue by naturepoker** [AstrobioMike/GToTree#36]
Hi, 

This question might not be directly related to GToTree - please let me know if I should ask in some other channel :) 

I'm working through the SCG set generation tutorial on your wiki - https://github.com/AstrobioMike/GToTree/wiki/SCG-sets 

The parallel download is done and now I need to extract and rename the header sections using the below script - but I can't seem to find the 'unzip_rename_cat_genes.sh' script itself anywhere in GToTree environment or the bits repo. Would you mind pointing me in the right direction?   

```
bash unzip_rename_cat_genes.sh all_genome_accs
```

Thank you!

**Comment by naturepoker** [comment]
Never mind, the script location is right in the same body of the text. For those who might be as careless as I am - 

curl -O https://raw.githubusercontent.com/AstrobioMike/AstrobioMike.github.io/master/misc/random_scripts/unzip_rename_cat_genes.sh

curl -O https://raw.githubusercontent.com/AstrobioMike/AstrobioMike.github.io/master/misc/random_scripts/pfam_counting.py

Don't I feel silly now :)

**Comment by AstrobioMike** [comment]
Ha, sorry for the confusion!

Also, I have (semi-secretly) introduced a program into GToTree that automates this process (working solely with NCBI accessions for input genomes), but it is kind of still in beta mode as I haven't been able to test it out that much yet – which is why I haven't put up an example/documented it yet. But if you wanted to try that, it's `gtt-gen-SCG-HMMs`. It uses the same conceptual steps as laid out on the SCG set wiki page (meaning scanning only for PFams with > 50% coverage of the underlying proteins, and retaining those with exactly 1 hit in the specified percentage of input genomes, default 90%). In case you want to try that :)

And if you do and happen to notice anything or have any thoughts, I’d appreciate the feedback :)
