### ISSUE TITLE
Some genomes return Est. %% comp: 0.00

### ISSUE THREAD

**Issue by anonymous7002** [AstrobioMike/GToTree#42]
Including these:

Homo sapiens: GCF_000001405.39
Rattus rattus: GCF_011064425.1
Helianthus annuus: GCF_002127325.2
Saccharomyces cerevisiae S288C: GCF_000146045.2

GToTree still finds all the genes for each forementioned accessions:
"Found 16 of the targeted 16 genes."

**Comment by AstrobioMike** [comment]
Thank you very much for reporting this! 

GToTree keeps track of total single-copy gene hits per genome as well as "unique" ones per genome, in the sense that they only show up once in a given genome rather than in multiple copies. And it was incorrectly calculating estimated completeness based on the number of "unique" hits. E.g., all of these "single-copy" genes show up multiple times in all but 1 of these eukaryotic genomes, so they weren't being counted at all towards the estimated completeness, and were coming back as 0. This was a much more insidious little bug with bacterial/archaeal genomes that generally only do have single copies of things, because it was only very slightly altering the estimated completeness. 

It is now fixed as of version 1.6.10.

Thanks again!

**Comment by anonymous7002** [comment]
All the 4 forementioned accessions appear on the same branch of a tree:

![firefox_7hApPCsmyv](https://user-images.githubusercontent.com/57062013/129470498-c1480730-6ae7-49d3-a1f5-7136b7d2e6ee.png)

**Comment by AstrobioMike** [comment]
Are you using ‘best-hit’ mode, specified with the `-B` option? Otherwise only genes that are in single-copy in the genome are being retained

**Comment by AstrobioMike** [comment]
After recreating this, I realize they still shouldn't have been making it through the workflow though. Due to the odd case with few genomes being run and all but 1 having only multiple hits to all targets, we were ending up with 1 target gene being considered (when not using "best-hit" mode (`-B`), and with the internal calculation of requiring 50% of target genes being found in a genome in order for it to be retained (default, set with `-G`), it was keeping those genomes with zero retained sequences instead of dumping them. This isn't something I'd seen with bacterial/archaeal datasets, I think that's why it escaped without anyone hitting it for so long. 

I added a check for this now, so in the future these won't make it through unless run in best-hit mode. This is implemented in v1.16.11 

(Though I realize this doesn't address [the download issue](https://github.com/AstrobioMike/GToTree/issues/43) i can't seem to recreate on linux or osx (and don't have a windows to test on) :/ so as of now that will most likely still be a problem)
