### ISSUE TITLE
new muscle support

### ISSUE THREAD

**Issue by jianshu93** [AstrobioMike/GToTree#48]
Hi Mike,

muscle release a new version 5, regular algorithm and the super 5 algorithm seems to be much faster than muscle 3.8 for large number of sequences. It is not yet available in conda so you many need to use the released binary.

Any thoughts?

Thanks,

Jianshu

**Comment by AstrobioMike** [comment]
Just realized this is what must have caused an issue just submitted earlier today https://github.com/AstrobioMike/GToTree/issues/47 thanks to you pointing this out to me. Thanks again, Jianshu!

**Comment by jianshu93** [comment]
woo！I actually checked yesterday！ Good timing！！

Jianshu

**Comment by jianshu93** [comment]
Hi Mike,

Some suggestions for using iqtree2 and new features added. In GoToTree line 3253 and 3255 (iqtree2 calling line), iqtree2 the newest version implement a very new bootstrap idea called Transfer bootstrap expectation (--tbe option in newest iqtree2), according to this paper: https://www.nature.com/articles/s41586-018-0043-0

As it pointed out that for larger number of sequences with deep branches, traditional Felsensteins's bootstrap method (used for the last ~40 years since publication in 1984) will lose phylogenetic signals while the transfer bootstrap expectation could reveal some signal. I think with GoToTree, users will be in that situation where they download some genomes from NCBI and then add their own genomes, several hundred genomes is possible and even a few thousand (why I think we should use muscle newest version, otherwise it will be too slow). So I suggest we use --tbe option to avoid that situation. It will be very similar speed. And the model you do not use automatic model finding algorithm, I understand it is for the speed, but you did test that the model is the best, at least most of the cases for concatenated universal gene?


Thanks,

Jianshu

**Comment by AstrobioMike** [comment]
thanks, Jianshu! 

**Muscle stuff**
Muscle5 is implemented as of GToTree v1.6.20 👍  

Something I didn't mess with yet, and maybe you'll have input on, is the number of threads used by muscle (the [-threads](https://drive5.com/muscle5/manual/cmd_align.html) argument). It defaults to number of CPUs, or a max of 20. When running multiple jobs with GToTree (set with the -j parameter), these are in theory multiplied during the alignment step (as each alignment job asks for that many threads right now), thereby allocating more threads than there are cpus. In my super-limited testing today with this specifically, and with prior experience in general, I don't really see that becoming a problem. As I think each cpu can handle multiple threads just fine typically, and a single thread going to a single cpu typically doesn't even remotely max out the cpu use (at least with how I see these terms used most often). But if you have better knowledge about this, and/or have thoughts on this as you use the new muscle specifically, please let me know what you think. We can always add an option to GToTree to set the number of threads muscle uses for each job, I just decided not to yet in order to avoid adding another option if it's not really necessary.

**iqtree stuff**
Thanks for the notes on this, and the info on the `--tbe` option. The iqtree run in GToTree is meant to be very generic, of course, like the rest of the workflow, and I recommend (like in the first section of the [things to consider page](https://github.com/AstrobioMike/GToTree/wiki/things-to-consider#an-important-caveat-on-the-idea-of-a-workflow-for-phylogenomics), and in the primary help menu with the [-T tree option description](https://github.com/AstrobioMike/GToTree/blob/0aba5da89a924db112c089176e9e9828ffa29bbd/bin/GToTree#L132)) if wanting to do more precise phylogenetics, the alignment file should be taken from GToTree (if we're ok with muscle) and used in a dedicated tree program where we have full control over all the options. I never actually wanted it to have more than just FastTree, in order to be more clear that this is high-level stuff, but a reviewer wanted another treeing option added. I've actually thought about removing iqtree altogether many times, but i know some people like using it in there already, so i've felt stuck. 

Now, with all that rambling off my chest, haha, there's no reason not to do things generic *and* better if that's possible, and I'm more than happy to modify how GToTree runs its "generic" iqtree run based on what you think. 

Quickly glancing through that paper, it seems like the `--tbe` option is fine to set as the standard run, right? Meaning it doesn't seem to have any downsides if used on smaller datasets? 

Regarding the model, I honestly don't remember why I settled on `-m WAG,LG`, letting model finder test only models based off of those, and I sadly can't find any logs/documentation from when I did – though I know i did spend some time on it when I put it in initially. Not using the full `-m MPF` model finder was definitely decided with consideration of time, because again I kind of feel like that's separate from the primary value that GToTree contributes (all the stuff up to that point). But I'm happy to change things on this if you have strong feelings about it. I'm not well-read or sharp on this stuff these days, and it seems you are :) Maybe, if nothing else, I could add another message when the program is started if it's with iqtree, noting again that some generic settings are being used for speed, but to consider taking the alignment alone and working with a dedicated treeing program? Please let me know if you have any thoughts/preferences on this

Thanks again for your knowledge and input!
