### ISSUE TITLE
Alphaproteobacteria (0 targets)

### ISSUE THREAD

**Issue by ebervilla** [AstrobioMike/GToTree#56]
Hi Mike

I hope you are doing well

I have been trying to construct a phylogenomic tree of rhizobia strains in GToTree using Alphaproteobacteria genes; however, apparently, GtoTree does not have any genes (see the attached picture of my console). Do you know what could I do to be able to construct the tree using alphaproteobacteria genes? 

Thank you very much for your help and for all the effort you put into your awesome tutorials

Best 

Eber

**Comment by AstrobioMike** [comment]
Hi there, Eber!

Thanks for the kind words :) Sorry it’s giving you trouble right now

I recently switched things such that GToTree downloads the specified SCG-set the first time it’s used and then stores it (to save a ton of space for those who don’t need all of them). It sounds like maybe something is not working there. But I think you forgot to attach the image. Can you put that in or copy/paste the output text for me?

**Comment by ebervilla** [comment]
Hi Mike

Yes, definitely it is necessary. Here I attached the outputs:

[output_gtotree_alphaproteobacteria.txt](https://github.com/AstrobioMike/GToTree/files/8445082/output_gtotree_alphaproteobacteria.txt)

[GToTree-v_gtt-data-locations_check.txt](https://github.com/AstrobioMike/GToTree/files/8445073/GToTree-v_gtt-data-locations_check.txt)

Thank you very much in advance

Best

**Comment by AstrobioMike** [comment]
Thanks, Eber!

Either way, this will help me implement a check that will catch this before trying to run everything else, and give an actually useful error message...

I'm wondering if the file tried to download but didn't finish successfully, but now it's not trying to download it because it is being found. See what size it is with:

```
ls -lh ${GToTree_HMM_dir}Alphaproteobacteria.hmm
```

If it's fully there, it should be ~8.3M.

Either way, try removing that with:

```
ls -lh ${GToTree_HMM_dir}Alphaproteobacteria.hmm
```

And then trying the main GToTree command again where you're specifying `-H Alphaproteobacteria`, and see if you get the same thing after you removed that file. I'm hoping it will download it again, and then you'll see this as the program starts, showing the expected number of targets:

```
    HMM source to be used:
      - Alphaproteobacteria.hmm (117 targets)
```

🤞

**Comment by AstrobioMike** [comment]
Great!

I'm going to leave this open until i implement a check to prevent this in the future

Thanks, Eber!
