### ISSUE TITLE
GTDB database update today

### ISSUE THREAD

**Issue by Tsingsjeen** [AstrobioMike/GToTree#57]
Hi,
I am going to download the GTDB representatives,
it reports errors as GTDB database updated, do you know how to solve this problem or ?

Great thanks!

**Comment by AstrobioMike** [comment]
Heya, @Tsingsjeen :) 

Thanks so much for the quick note on this! It was indeed due to the [switch](https://data.ace.uq.edu.au/public/gtdb/data/releases/latest/RELEASE_NOTES) from 122 archaeal genes to 53 in the latest release, causing the archaeal url with the 122 in it to not be found. 

This is fixed now as of version 1.6.34. So removing the old conda environment and doing a fresh install should solve it 👍 

Thanks again for writing in right away so I knew to address this!

**Comment by Tsingsjeen** [comment]
Thanks Mike! Now, it worked!
