### ISSUE TITLE
Muscle Thread Usage

### ISSUE THREAD

**Issue by raufs** [AstrobioMike/GToTree#59]
Hi Mike,

Thanks for developing this awesome program!

For muscle align/super5 it seems the default is to use 20 threads when available, can you please have it's thread usage be controlled via the `-n` argument of GToTree.

It seems this can be done with the `-threads` argument:

https://drive5.com/muscle5/manual/cmd_super5.html

Kind regards,
Rauf

**Comment by AstrobioMike** [comment]
Hey there, Rauf!

Thanks for the kind works and suggestion :) 

I added a new flag for it (`-M`) just because i wanted to keep it separate from what is specifying for the HMM search (i know at least i would generally want this to be higher, while for the HMM searching, lower is fine). It is implemented as of version 1.6.35, which is already updated in conda 👍 

Thanks again!
-Mike

**Comment by raufs** [comment]
Wow that was fast! Thank you, that makes sense and sounds perfect! 

Greatly appreciated!
Rauf
