### ISSUE TITLE
Keeping more than the best hit

### ISSUE THREAD

**Issue by sergiophyceae** [AstrobioMike/GToTree#6]
Thanks for the great software! I was wondering whether you could add an option to keep more than the best hit only. This would be useful for some phylogeneticists that prefer to more carefully inspect single-gene trees to discard the non-orthologs. One option would be for GToTree to create an additional set of files in the temporary directory without really affecting the main output. Thank you!

**Comment by AstrobioMike** [comment]
Hi there, Sergio!

Thanks for using it/checking it out and for the suggestion :) 

I like the idea of adding an option to do this, for those that are interested so they can more easily look into things, but not being default it wouldn't add more computational time and storage-usage to those that aren't look at it. 

But it will take me a bit of time to get to it. Right now I dump the original sequence and/or gene headers as soon as possible to something simpler to make sure there are no potentially wonky characters carried along further than needed. I'm sure i can add in making an initial mapping file for each gene at the time of doing each genome, and then if duplicates are found then i could report them with the initial gene identifiers (for those that have initial input genes). But it's not a quick addition i can do unfortunately. 

For now, there is a table reported that shows the number of hits per target gene per genome that you've probably already noticed (in the output directory in a file called "All_genomes_SCG_hit_counts.tsv"). That could be looked at, and then the user can pull and search those genes/genomes of interest specifically on their own starting from there if they are going to get into individual-gene-level trees. 

But I will work on implementing this option though as soon as I can, because I do think it would be a nice convenience. 

Thanks again for the suggestion! 
-mike

**Comment by AstrobioMike** [comment]
Thanks again for suggesting this. But i'm gonna sort of quietly close this, ha, as it hasn't come up as a feature request again, which I was kind of waiting for. I always have other robustness and efficiency things I need to improve whenever I can work on GToTree, if not other feature requests with generally more utility to more folks, so this will keep getting bumped until there is more demand for it :/ (I'm sure you weren't holding your breath!)
