### ISSUE TITLE
Problem downloading the Actinobacteria.hmm

### ISSUE THREAD

**Issue by oduwoleiyanu** [AstrobioMike/GToTree#66]
I got this error while using the GToTree for phylogenomics. Is there something I can do to fix that.

/home/ioduwole/miniconda3/envs/gtotree/bin/GToTree: line 1008: curl: command not found
md5sum: /home/ioduwole/miniconda3/envs/gtotree/share/gtotree/hmm_sets/Actinobacteria.hmm: No such file or directory

      There seems to have been a problem downloading the Actinobacteria. hmm file :(
      Please try again, and if problems continue, please report an issue here:
              https://github.com/AstrobioMike/GToTree/issues

**Comment by AstrobioMike** [comment]
Hiya, @oduwoleiyanu :) 

Sorry about that! I didn't mean to expect curl to be present, or need to make the user install it (especially without telling anyone!). It looks like i forgot to include curl in the conda package, and it just hasn't come up yet. To be sure, you installed curl on your own in order to get around this?

**Comment by AstrobioMike** [comment]
Never mind, i added it now regardless which i think it needed. Thank you for writing in about this!

(added to conda build as of v1.7.05 build 1)
