### ISSUE TITLE
provide protein sequence or hmm for searching in lieu of pfam

### ISSUE THREAD

**Issue by spleonard1** [AstrobioMike/GToTree#73]
Hey! What spectacular software thank you so much for making it!

Is it possible to supply a protein fasta file or set of hmm profiles to check for presence absence in lieu of the pfam (-p) option? I'm not used to navigating pfam and having a little trouble finding what I want now that it's (sort of?) deprecated?  

Great walkthroughs, too, as usual :)

**Comment by AstrobioMike** [comment]
thanks for the kinds words, @spleonard1 :) 

sorry there is that there is this other big issue (https://github.com/AstrobioMike/GToTree/issues/74) right now!

I don't have a way built in to take any protein sequences, and no capacity for custom HMMs yet in terms of tracking presence/absence :( 

You may have noticed, but searching for KO terms is also currently supported, rather than pfams. You could look for your function(s) of interest [here](https://www.genome.jp/kegg/ko.html) by text searching for functions or [here](https://www.genome.jp/brite/ko00001) by clicking through different groupings. Then once having the wanted KO IDs, they would just go in a single-column file, e.g.:

```
K08197
K18979
```

which would then be passed to the `-K` option in the `GToTree` call

But other ways outside of using those 2 dbs aren't available currently, unfortunately. I don't really have plans for incorporating taking just sequences (just because there are so many decisions to be made about how to look for them and call things a "hit" or not), but eventually i'd like to incorporate being able to take custom HMMs for this purpose. It just probably won't be for a while still.

**Comment by spleonard1** [comment]
Sounds good! Thanks for the extra info. No worries at all, this would be a "nice to have" feature but not essential, and there are other ways to do it. Feel free to close this issue.
