### ISSUE TITLE
installation instructions with only software dependencies in conda env

### ISSUE THREAD

**Issue by taylorreiter** [AstrobioMike/GToTree#8]
I am trying to us GToTree in a snakemake workflow. I would like to specify a conda environment for the dependencies, something like this:

```
channels:
   - conda-forge
   - bioconda
   - defaults
dependencies:
   - biopython
   - hmmer=3.2.1
   - muscle=3.8.1551
   - trimal=1.4.1
   - fasttree=2.1.10
   - iqtree=1.6.9
   - prodigal=2.6.3
   - taxonkit=0.3.0
   - gnu-parallel=20161122
```

and then be able to to run GToTree from this environment. I've figured out how to point to the hmm-sets I would like to use, but I don't know how to point to the ncbi tax files, or how to refer to each script that is orchestrated by `GToTree`. Do you have any recommendations for how I can orchestrate this? Or would you be willing to make GToTree a conda-installable package? :)

**Comment by AstrobioMike** [comment]
So thanks to your extra motivation boost to me to return to Conda struggles, and thanks to the awesome powers of @ebolyen saving me days of struggling, GToTree is now conda installable :) 

https://github.com/AstrobioMike/GToTree/wiki/Installation#conda-quickstart

We're working on getting it on bioconda instead of my own channel, but that may be a while.

Thanks for making me care about this again, @taylorreiter!

**Comment by taylorreiter** [comment]
Yay!!!! Thanks @AstrobioMike & @ebolyen!
