### ISSUE TITLE
GTDB metadata URL change

### ISSUE THREAD

**Issue by ThinkPad254** [AstrobioMike/GToTree#88]
Dear GToTree Developers,

I hope this message finds you well. I would like to start by expressing my deep appreciation for your work on GToTree. It has significantly improved the efficiency of our research processes, and for that, we are extremely grateful.

I am writing to report an issue I encountered while using the `gtt-get-accessions-from-GTDB` command. Specifically, I encountered an `HTTP Error 404: Not Found` when the command attempted to access a URL that appears to be outdated. The error suggests that the script tries to download data from `https://data.gtdb.ecogenomic.org/releases/latest/ar53_metadata.tar.gz`, but it seems the file format has changed from `.tar.gz` to `.tsv.gz` based on the current resources available at GTDB. It appears the correct URL should now be `https://data.gtdb.ecogenomic.org/releases/latest/ar53_metadata.tsv.gz`. Could you please update the script to reflect the new URL? Such an update would greatly assist us and potentially other users who might be facing the same issue.

Thank you very much for your attention to this matter and for your continued support in enhancing the research community's tools and resources.

Best regards,
Tony

**Comment by AstrobioMike** [comment]
Hi there, Tony!

Thanks for the kind message and for writing in, sorry for the issue

Do you know which version of GToTree you are having this happen with (you can check with `GToTree -v`)?

This should have been addressed as of i think version 1.8.3, we can see the spot in the code [here](https://github.com/AstrobioMike/GToTree/blob/ca7ea3528b46e1fc5007765bcc99f9b7b1497af9/bin/gtt-get-accessions-from-GTDB#L409) has the right link. Can you confirm if you have an older version? Otherwise maybe i'm missing an older link somewhere else in another helper script...
