### ISSUE TITLE
gtt-align-and-trim-parallel killed + alignment not loaded error

### ISSUE THREAD

**Issue by shrdlu9** [AstrobioMike/GToTree#9]
Hi, 

Thanks for the amazing package - we've been having a blast with it on what I'm hoping will be my first paper. 

I've been encountering a strange issue with the package lately though - on very large genome datasets the process throws below error during ribosomal gene aligning and formatting step (on Universal setting). 

Copying and pasting terminal output below 

      Finished aligning and formatting gene-set Ribosomal_L16.

/home/mainc/anaconda3/envs/gtotree/bin/gtt-align-and-trim-parallel.sh: line 14:  6780 Killed                  muscle -in ${tmp_dir}/${1}_hits_filtered.faa -diags -maxiters 4 -out ${tmp_dir}/${1}_aligned.tmp &> /dev/null

ERROR: Alignment not loaded: "1572795484.gtotree.tmpdir/Ribosomal_L16_aligned.tmp" Check the file's content.

sed: can't read 1572795484.gtotree.tmpdir/Ribosomal_L16_trimmed.faa.tmp: No such file or directory

      Finished aligning and formatting gene-set Ribosomal_L14.

/home/mainc/anaconda3/envs/gtotree/bin/gtt-align-and-trim-parallel.sh: line 14:  6790 Killed                  muscle -in ${tmp_dir}/${1}_hits_filtered.faa -diags -maxiters 4 -out ${tmp_dir}/${1}_aligned.tmp &> /dev/null

ERROR: Alignment not loaded: "1572795484.gtotree.tmpdir/Ribosomal_L14_aligned.tmp" Check the file's content.

sed: can't read 1572795484.gtotree.tmpdir/Ribosomal_L14_trimmed.faa.tmp: No such file or directory

Not all ribosomal aligning/formatting gives above error messages. 
I thought maybe it's just the system running out of memory, so tested the script again on a dataset we were previously able to get a phylogenetic tree and pfam extraction out of without any error messages. We're now getting error messages on the previously successful dataset as well. There's still about 25GB ram and a couple of hundred GB of space left on the machine, and no other process was running on the hardware at the time. 

The dataset in question is about 14k bacterial genomes. 

What could the issue be?   

Thanks!

**Comment by AstrobioMike** [comment]
Hmm, thanks so much for sending this in. Unfortunately I have no quick insight or help to offer. It is strange you’re getting similar error messages on an input set of genomes that previously finished ok. That too makes me wonder if it’s about storage somehow during the run. This is going to be one of those things that because I know very little about computer science, it’s going to take me a bit to track down - when it might be obvious to someone who actually understands what the computer is really doing under the hood, ha. 

I’m going to start running some tests tracking memory and storage usage on large and small datasets, on a system with tons of storage and memory and one with very little and see if I can recreate this. 

In the very least it’d be nice to have some checks in place to see if this is happening and give an actually informative error message. 

Is your input of ~14,000 genomes made up of those with NCBI accessions, or publicly available things that I could work with if you just sent me a list of IDs or something? Probably doesn’t matter if I’m working with another large set, but using the same if possible would be safer in trying to find the problem

Thanks again for sending this in!

**Comment by shrdlu9** [comment]
Hi, 

Thank you for responding! Of course, including the accessions list we were using for the run. 

Let me know if you might need anything else. 

[0918-test-accessions.txt](https://github.com/AstrobioMike/GToTree/files/3847882/0918-test-accessions.txt)

**Comment by AstrobioMike** [comment]
Thanks! Sorry for the issue :/ 

I'll get back to you soon :)

**Comment by AstrobioMike** [comment]
So I am pretty sure RAM was the problem, depending on how many alignments were running at the same time – what we're setting with the `-j` parameter. 

For example, when running with `-j 10`, ten alignments are run concurrently, and with this many genomes (genes being aligned) that can start to add up in memory costs. I'm running these ~14k genomes with 10 like that now, and I already exceeded 50 GB memory usage before any of the first 10 gene-sets have finished aligning. It's not a perfect relationship, but it's safe to assume this probably would have run out of 25 GB of memory even if running with `-j 5` at this point, and it's still going up, so maybe even would have run out with fewer concurrent alignments. Do you remember what you had for `-j`  when it failed for you? 

I wonder if when you ran that previously successful dataset a second time, and hit the same issue as above, did you increase the `-j` parameter from the first time you did it? Meaning it might not have run out of memory when run as something like `-j 2`, but could run out of memory with `-j 10`, for instance. 

I am realizing i haven't made a tree with this many genomes yet, haha, i think the most i've done was like 6,000. I maybe should look into adding an aligner with a smaller memory footprint to enable doing genomes at this scale still when there is a lower amount of memory available. 

This is going to be super-helpful to add to the ["Things to consider page"](https://github.com/AstrobioMike/GToTree/wiki/things-to-consider), and to the documentation on selecting `-j`, so thanks again for bringing my attention to it :) 

And I'll let you know what the max memory usage is that I see with this run when it's done
