### ISSUE TITLE
Using  gtt-data-locations set with singularity image

### ISSUE THREAD

**Issue by nandan75** [AstrobioMike/GToTree#93]
Hi,

Thanks for making this wonderful tool.

I am using the singularity image of the gToTree tool from `https://quay.io/repository/biocontainers/gtotree?tab=tags`

When trying to set the `gtt-data-locations` using 
`gtt-data-locations set`

I get the followign error.

```
We can't seem to find a place to store startup environmental variables
  :( '
  This is likely due to permission restrictions in the conda environment
  location, and in your home location.
```

I wanted to use your tool to be part of my nextflow pipeline. 

Appreciate any assistance,

regards,

Nandan

**Comment by AstrobioMike** [comment]
Hi there, Nandan, 

Did you think I would forget you asked this before (https://github.com/AstrobioMike/GToTree/issues/86), and I'd feel more pressure because more people were requesting it? Haha :) (not a bad play if so!)

Sorry, I still haven't been able to put time into getting things to work via Singularity. I took at peek at it, but I wasn't able to set locations for the needed reference files where there are write permissions inside the container. I'm sure there are ways to deal with this, but i just don't know them and haven't been able to sort it out :/

**Comment by nandan75** [comment]
Oops my bad- I completely forgot my own query :-) No way I was trying to
pressurise you.

It is just that I tried a few other tools on the way such as Phylophlan3
etc and found a few singularity related issues there and then came back to
check on your good tool . And completely lost track that I had pestered you
before. My apologies.

regards,

Nandan

**Comment by AstrobioMike** [comment]
Haha, all good! I feel for you still trying to find a path that works for you :/ Wish I had better news from my end!
